const CELL_MIN_COLUMNS = 3
const CELL_PORTRAIT_MULTIPLIER = 0.3
const CELL_LANDSCAPE_MULTIPLIER = 0.2
const TABLE_MARGIN_HORIZONTAL = 20
const SAFE_AREA_PORTRAIT_WIDTH = 150

export {
  CELL_MIN_COLUMNS,
  CELL_PORTRAIT_MULTIPLIER,
  CELL_LANDSCAPE_MULTIPLIER,
  TABLE_MARGIN_HORIZONTAL,
  SAFE_AREA_PORTRAIT_WIDTH,
}
